// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqnxrPgzTr_k1hzqMt5Xx0DwPeTCZWfc',
    appId: '1:662728775064:web:401ff8093decf7e39b47ed',
    messagingSenderId: '662728775064',
    projectId: 'not-uygulamasi-3ddbf',
    authDomain: 'not-uygulamasi-3ddbf.firebaseapp.com',
    storageBucket: 'not-uygulamasi-3ddbf.firebasestorage.app',
    measurementId: 'G-GXYTY4595Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRIjGaDoYg42pql3KmUGXg_kAzl4_ArCQ',
    appId: '1:662728775064:android:74ff791adf62ad3e9b47ed',
    messagingSenderId: '662728775064',
    projectId: 'not-uygulamasi-3ddbf',
    storageBucket: 'not-uygulamasi-3ddbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuB8l3yTtyMZPZkzTViYNj0lVTLztpT9U',
    appId: '1:662728775064:ios:ef1b700f1f8627a69b47ed',
    messagingSenderId: '662728775064',
    projectId: 'not-uygulamasi-3ddbf',
    storageBucket: 'not-uygulamasi-3ddbf.firebasestorage.app',
    iosBundleId: 'com.example.notUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuB8l3yTtyMZPZkzTViYNj0lVTLztpT9U',
    appId: '1:662728775064:ios:ef1b700f1f8627a69b47ed',
    messagingSenderId: '662728775064',
    projectId: 'not-uygulamasi-3ddbf',
    storageBucket: 'not-uygulamasi-3ddbf.firebasestorage.app',
    iosBundleId: 'com.example.notUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyqnxrPgzTr_k1hzqMt5Xx0DwPeTCZWfc',
    appId: '1:662728775064:web:ebfc7d54103d7be39b47ed',
    messagingSenderId: '662728775064',
    projectId: 'not-uygulamasi-3ddbf',
    authDomain: 'not-uygulamasi-3ddbf.firebaseapp.com',
    storageBucket: 'not-uygulamasi-3ddbf.firebasestorage.app',
    measurementId: 'G-Z1G0SKB7TB',
  );
}
